# paths in config.yml are either an absolute path or relative to the repo directory

dataset:
  train:
    module_name: fake
    kwargs:
      dataset_dir: data/k700-2020
      n_references: 3
      n_samples: 10
      batch_size: 32
      shuffle: True
      frame_rate: 6


transform:
  train:
    input:
      - module_name: v2ToImage        # torchvision.transforms.v2.ToImage
      - module_name: v2ToDtype        # torchvision.transforms.v2.ToDtype
        kwargs:
          dtype: torch.float32        # must be torch native dtype
          scale: True
      - module_name: v2Resize         # torchvision.transforms.v2.Resize
        kwargs:
          size: [256, 256]            # [height, width]
          antialias: True
      - module_name: v2Grayscale      # torchvision.transforms.v2.Grayscale
    label:
      - module_name: cv2Resize
        kwargs:
          size: [32, 32]              # [height, width]
      - module_name: cv2cvtColor
        kwargs:
          code: cv2.COLOR_BGR2LAB
      - module_name: ExtractChannel
        kwargs:
          channels: [1, 2]
      - module_name: Quantize
        kwargs:
          model:
            module_name: KMeans
            kwargs:
              n_clusters: 16
          encoder: OneHotEncoder
          checkpoint_path: checkpoints/transform/Quantize # path to checkpoint dir (get the latest) or a specific checkpoint file
          

model:
  backbone:
    module_name: resnet18
    kwargs:
      stage_channels: [64, 128, 128, 256]
      stage_strides: [1, 2, 1, 1]

  head: convnet3d



training:



validation:



predict:



logging:
  level: INFO
  format: " %(asctime)23s | %(module)10s | %(funcName)20s | %(lineno)5d | %(levelname)8s | %(message)s"
  handlers:
    file: logs   # directory to save log files
    stream: stdout
  datetime_format: '%Y%m%d_%H%M%S'